"use client";
import { ReactLenis } from "@studio-freight/react-lenis";
import { ReactNode } from "react";
import Navbar, { NavbarContextC } from "./components/Navbar";
import "./globals.css";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }: { children: ReactNode }) {
  // const lenis = useLenis(({ scroll }: { scroll: any }) => {
  //   // called every scroll
  // });
  return (
    <html lang="en">
      <body className="bg-light-primary w-screen h-screen overflow-x-hidden text-light-secondary">
        <NavbarContextC>
          <ReactLenis root>
            <Navbar />
            {children}
          </ReactLenis>
        </NavbarContextC>
      </body>
    </html>
  );
}
